### ISSUE TITLE
Cashdrawer Kicker not always firing with Metapace K-1/m30-BT

### ISSUE THREAD

**Issue by pc-coholic** [pretix/pretixprint-android#15]
One of our customers using a Metapace K-1 is experiencing issues with a TM-m30 (BT-Connectivity): Every now and then, the cashdrawer is just not kicking open.

https://github.com/pretix/pretixprint-android/blob/a2f7cb3cbbb80cc4d8eb45cb7ffa757f120628ff/pretixprint/app/src/main/java/eu/pretix/pretixprint/print/ESCPOSRenderer.kt#L116-L117

I think there are two things we could do:
- Increase the opening-interval or make it configurable (or at least test it against the HP cashdrawer, too)
- Send the opening impulse twice in case one of them gets lost

Besides that, this might also just be a Bluetooth-issue, since printing the fiscalisation QR-code also gets interrupted and had to be disabled... So perhaps our BT-stack is not flushing out completely? If that was the case, we could potentially ask a customer to put their printer into hex-debug-mode, send a receipt and check if it arrives completely or if some bytes are cut off...

Ref: Z#2381327

**Comment by raphaelm** [comment]
Unless we have any indication this is really cutter-specific, I think it's just a general bluetooth issue that is "solved" by our general delay we already offer.
