### ISSUE TITLE
Play Protect

### ISSUE THREAD

**Issue by west89** [pretix/pretixprint-android#5]
During the installation the Play Protect strikes and blocks the installation

![Screenshot_20191214-110226](https://user-images.githubusercontent.com/42120960/70847154-449ca900-1e61-11ea-8185-531ed499863b.jpg)

**Comment by raphaelm** [comment]
Huh, this is new. Anyone knows how to debug such a thing?

**Comment by pc-coholic** [comment]
I cannot reproduce this on my device - even forcing a fresh check will pass the app... So this might be a temporary/local malfunction on the device performing the check?

Apart from that, we could try to file an appeal: https://support.google.com/googleplay/android-developer/contact/protectappeals?hl=en

**Comment by raphaelm** [comment]
Oh, is that screenshot from F-Droid? Then I guess that's kinda expected (and even true!) since the app is not signed by us.

**Comment by west89** [comment]
> Oh, is that screenshot from F-Droid? Then I guess that's kinda expected (and even true!) since the app is not signed by us.

The screenshot is Aurora Droid
The app is from the F-Droid repository.

![Screenshot_20191214-132854](https://user-images.githubusercontent.com/42120960/70848703-b67eed80-1e75-11ea-8a39-7725216d0b51.jpg)

**Comment by raphaelm** [comment]
Yeah, well, I think Google Play Protect is doing it's job correctly here. ;)
