### ISSUE TITLE
FGL printer doesn't include page setup

### ISSUE THREAD

**Issue by AlexanderMohan** [pretix/pretixprint-android#51]
Hi,

I'm unable to change any page setup actions for an FGL printer, thus it is printing at the wrong length for our ticket stock, and I have to shrink the DPI for the pretix ticket to fit on the stock.

Is there any solution/workaround for this?

**Comment by raphaelm** [comment]
If your PDF has the correct size and the DPI is set correctly, it should just work.

- What exact printer do you have?
- What is your paper size?
- Can you show a sample PDF?

**Comment by AlexanderMohan** [comment]
This seems like a simpler solution then that I didn't realise existed - how do you set the PDF that pretixPOS uses? Is it the Mobile format one? I can't see any option in pretixPOS.

**Comment by AlexanderMohan** [comment]
Found the solution, this is not an app problem so closing the issue.
